# Generated by Django 4.1.3 on 2022-12-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackimage',
            name='image',
        ),
        migrations.AddField(
            model_name='observation',
            name='photo_permission',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('C', 'Please contact me before use')], default='Y', max_length=1, verbose_name='Do you grant Cascades Wolverine Project permission to share your images publicly on our website or social media. (Photo will be credited to the name submitted in this form unless you ask for something different in the notes field of this form)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackimage',
            name='file',
            field=models.FileField(default='', upload_to='track_images/%Y-%m-%d--%H-%M/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_type',
            field=models.CharField(choices=[('T', 'Tracks'), ('D', 'Direct observation of an animal'), ('B', 'Both')], max_length=1, verbose_name='Footprints or Animal Observation'),
        ),
    ]
