# Generated by Django 4.1.3 on 2022-12-11 05:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_review_suspected_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='diagnostic_features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('size_range', 'Size range is correct'), ('shape', 'Overall shape of individual tracks is correct'), ('morphology', 'All details in clear print are correct for the morphology of a wolverine foot'), ('pattern_and_size_diagnostic', 'Track pattern and size is diagnostic for only a wolverine'), ('no_counterindications', 'There are no features in individual tracks or trail that counter-indicate a wolverine')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
