# Generated by Django 4.1.3 on 2022-12-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_alter_review_diagnostic_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='track_identification_score',
            new_name='identification_score',
        ),
    ]
